### ISSUE TITLE
自己新添加马赛克滤镜类型，出现程序异常退出

### ISSUE THREAD

**Issue by lijunsxr** [Martin20150405/Pano360#12]
新添加马赛克glsl滤镜，新建一个滤镜类型类
public class MxMasaikeFilter  extends MxOneHashBaseFilter{
    public MxMasaikeFilter(Context context) {
        super(context, "filter/fsh/mx_masai.glsl");
        rgbMap = new int[]{.....};
    }
}

**Comment by Martin20150405** [comment]
你这样贴我看不出问题的呀。。
可以参考[这个项目](https://github.com/Martin20150405/Omoshiroi)的马赛克滤镜，格式差不多
