### ISSUE TITLE
初始方向问题

### ISSUE THREAD

**Issue by cnsms** [Martin20150405/Pano360#14]
其他播放器播放的时候，不管哪个方向播放的时候，都是从正视角开始的，这个播放器正视角是默认一个方向的，不会根据手机的方向自动调整，这是哪里没有设置对吗？

**Comment by Martin20150405** [comment]
设置lockAxisMode为LOCK_MODE_AXIS_Y
或者换md360的cardboard模式

**Comment by cnsms** [comment]
是这样的，我想让视角开始就以LOCK_MODE_AXIS_Y这个界面，然后随着手机转动继续调整界面。

**Comment by cnsms** [comment]
大神，应该怎样实现呢？在线等

**Comment by cnsms** [comment]
还是没解决

**Comment by Martin20150405** [comment]
建议你换MD360,然后去VR交流群里面问下

**Comment by cnsms** [comment]
可是我不想放弃您的项目呢
