### ISSUE TITLE
你陀螺仪漂移怎么处理的?

### ISSUE THREAD

**Issue by liupeng110** [Martin20150405/Pano360#2]
还有视角角度有点歪  怎么调整一下

**Comment by Martin20150405** [comment]
旋转矢量传感器默认会用加速度和磁场来校准

LOCK_MODE_GAME_ROTATION_VECTOR的具体实现是记录一开始绕Y轴（和重力方向相反）的旋转角，然后每次都转回去这个角度

陀螺仪是会漂移的，但是旋转矢量传感器会自动校正，我没有进一步处理

视角歪了的话，可能和手机的传感器有关，如果所有手机情况一样，可以直接绕Y轴和X轴校正一定角度

**Comment by liupeng110** [comment]
初始化角度呢

**Comment by Martin20150405** [comment]
Please read the statement carefully and refer to the code.

**Comment by liupeng110** [comment]
楼主你这个也会受磁影响,但是会自动转回去   md360那个不会转回去
能不能把你的处理方式移植到md360那个库 
 因为md360的库其他地方处理的相对完善一些,那样直接就可以在项目里用了

**Comment by Martin20150405** [comment]
看来你已经用cardboard解决了这个问题。。
