### ISSUE TITLE
求教前辈

### ISSUE THREAD

**Issue by like001** [Martin20150405/Pano360#3]
Martin，您好！看了您的git项目和csdn博客，很受启发，多谢多谢。我想了解更多关于全景视频播放相关的实现原理，不知道有没有这方面的介绍书籍或者资料推荐的呢？在网上查了很多，都是很浅显的层面，您的博客已经是最详实的了。您这边把所有的技术细节都已经代码实现了，想必会有很详细的参考文档吧，可以介绍一下资料的获取渠道吗？先行谢过！

**Comment by Martin20150405** [comment]
前辈。。感觉好方。。
你说的"更多关于全景视频播放相关的实现原理"，不知道是指什么呢？因为如你所见，整个流程和原理都不复杂。。
其实并没有很多的参考文档，如果你对这方面感兴趣的话，有这几个方面的知识可以去了解：图形学、传感器、视频编解码，如果想基于android和ios开发原生的播放器，那官方文档肯定是要好好看的
另外，可以关注一下cardboard vr的相关原理，这样能做出来的东西就远不止全景视频播放这么简单了
