### ISSUE TITLE
双屏播放普通的2D或3D视频有问题

### ISSUE THREAD

**Issue by shaodong2528** [Martin20150405/Pano360#4]
我在播放普通的视频时，采用了双屏模式，但有点不正常，因为感觉视频都被处理成球型来显示的，有拉伸和扭曲的感觉

**Comment by Martin20150405** [comment]
@shaodong2528 
这个功能的UI我还没做
如果要放普通视频的话，把`PanoRender`类里面的`filterGroup.addFilter(spherePlugin);`删掉就好了 （可以自己加个判断是普通还是全景）
我会在2017/02/10前更新平面视频的缩放选项（铺满STRETCH、适应FIT、切割CROP）

**Comment by Martin20150405** [comment]
@shaodong2528 
已经更新


> 把PanoRender类里面的filterGroup.addFilter(spherePlugin);删掉就好了

改成修改`PLANE_VIDEO`常量确定是什么播放模式(支持铺满和自适应屏幕，双屏请自己加上)

这部分的工作还没完成，等我有时间会再更新
