### ISSUE TITLE
How to remove the orange placeholder displaying your email id from the player?

### ISSUE THREAD

**Issue by abhiank209** [Martin20150405/Pano360#8]
Hey Martin, 

Thanks for building this awesome library. Really glad this exists. 

I'm trying to stream 360-degree youtube video in my app using your library, however, I don't wish to see the orange round icon in the center of the video which displays your email id. How can I remove that from the player?

**Comment by Martin20150405** [comment]
@abhiank209 
Hahahaha...
I'll provide an interface to control plugins in future version.
If you want to move it now,  just delete all `hotSpotList.add(hotSpot);` like sentences.
Sorry for trouble caused.

**Comment by abhiank209** [comment]
Cool! Thanks. There's another issue regarding the timer text; I've fixed it. I'll create a PR soon.
